---
title: "Project 1"
output: html_document
---
###Connect to the Oracle Database###

```{r}
source("../01 Data/project1.R", echo=TRUE)
```

###Display Data Frames###
```{r}
head(customers)
head(items)
head(order_details)
head(orders)
```


###Interesting Plots###
```{r}
library(ggplot2)
ggplot(customers, aes(x=CUSTOMER_STATE, y=CUSTOMER_CITY, color=CUSTOMER_ZIP)) + geom_point()

ggplot(items, aes(x=ARTIST, y=UNIT_PRICE)) + geom_bar(stat="identity")

ggplot(order_details, aes(x=ITEM_ID, y=ORDER_QTY)) + geom_bar(stat="identity")

MONTHS <- as.numeric(substring(orders[,3], 6, 7))
DAYS <- as.numeric(substring(orders[,4], 9, 10)) - as.numeric(substring(orders[,3], 9, 10))
DAYS[5] <- 10
DAYS[7] <- 4
DAYS[14] <- 12
DAYS[17] <- 26
DAYS[21] <- 6
DAYS[22] <- 32
DAYS[26] <- 26
DAYS[27] <- 10
DAYS[29] <- 9
DAYS[30] <- 9
DAYS[35] <- 13
DAYS[36] <- 9
DAYS[45:47] <- 0
ggplot(orders, aes(x=MONTHS, y=DAYS)) + geom_bar(stat="identity")
```

###Query###
```{r}
entire <- data.frame(eval(parse(text=substring(getURL(URLencode('http://129.152.144.84:5001/rest/native/?query="select * from orders o join customers c on o.customer_id = c.customer_id join order_details d on o.order_id = d.order_id join items i on d.item_id = i.item_id"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521/PDB1.usuniversi01134.oraclecloud.internal', USER='DV_ORDERS', PASS='orcl', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

head(entire)
```

###Produce Plots###
```{r, warning=FALSE}
ggplot(entire, aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"))) + geom_point(aes(color=as.factor(UNIT_PRICE))) + facet_wrap(~CUSTOMER_STATE)

ggplot(entire, aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"))) + geom_point(aes(color=as.factor(TITLE))) + facet_wrap(~CUSTOMER_STATE)

ggplot(entire, aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"))) + geom_point(aes(color=as.factor(ARTIST))) + facet_wrap(~CUSTOMER_STATE)
```